### PR TITLE
Add main figure 4

### PR DESCRIPTION
**Pull request by jenna-tomkinson**
# Add main figure 4

In this PR, main figure 4 is generated to show the feature importances of the model and display min/max image montages of the top features for Null cells. Main figure 3 was also updated in this PR per request for update for presentation.

### CODE REVIEW

**Comment by gwaybio** [comment]
Nitpicks

- I don't like how neighbors and areashape looks all isolated like this. Perhaps we could add these two coefficient categories in a separate plot (but still labeled as panel A)?
- The correlation feature group is really two different channels. I think we should clarify what two channels are correlating in a separate, square plot per compartment
- The y axis probably should be `Feature group` (not `Feature`)

See https://github.com/broadinstitute/profiling-resistance-mechanisms/blob/master/5.signature-exploration/5.visualize_signature.ipynb as an example of a potential upgrade

**Comment by gwaybio** [comment]
Second round nitpicks:

- Please add back the organelle names rather than the channel names for the lower coefficient plot
- I don't think we need to show all the different feature measurements for AreaShape. They are less important so ok to collapse into a single square per compartment
- What happened to the neighbors feature group? I think this is important to point out that neighbors didn't have important influence in the model
- I think there should be a way to group the legend in patchwork. (i.e., there is no need to duplicate the same legend three times)
- Depending on how your planning on visualizing example images for each top coefficient, it might make sense to add the AreaShape/Neighbor portion above the the plot (adding whitespace too)

**Comment by gwaybio** [comment]
These edits look great! I'm excited to review the figure after adding montages

**Comment by gwaybio** [comment]
Montage nitpicks (we discussed this in person)

- Make all coefficient plots panel A (only go to panel C)
- The two bottom right cells are the same image
- Let's focus on the ER intensity feature (keep the correlation feature for potential use in the supplement)
- It might be nice to include an asterisk on panel A for the features that you'll visualize in the panels below (Extra Credit)

**Review by gwaybio — APPROVED** [review]
Looks great! 🤩 

My one nitpick is that the red asterisk might look a bit funny (or be invisible) to someone with red/green colorblindness. I recommend making the asterisk white.

Feel free to merge at will!

**Comment by jenna-tomkinson** [comment]
@gwaybio Great point! I addressed that last comment, and I will merge it now. Thank you for the reviews!

**Pull request merged**
