### PR TITLE
Remove older analysis

### PR DESCRIPTION
**Pull request by MattsonCam**
This pr aims to software garden this repo by removing older analysis. Please give any constructive feedback while reviewing this pr.

### CODE REVIEW

**Comment by MikeLippincott** [comment]
Questions: 
- Why remove older analysis? 
- Could these be used in the future? 
- Are there any analysis that could be used as supplemental? 
- Could these analyses be refactored to a misc analysis folder?

Negative results or analyses that did not work or were published are still important analyses and thus might have reason to stay in the repo depending on how you answer the above questions.

**Review by jenna-tomkinson — CHANGES_REQUESTED** [review]
Here is a screenshot of what the repo will look like after this PR:
image
Some comments based on the new structure of the repo from this branch:
1. I would recommend not having the "classify_genotypes" module if you plan on only having one method. It looks a bit odd to me in the screenshot to have two modules with the same folder name inside.
2. In the 0.data_analysis repo, I recommend that you should leave the plate 4 analysis. Even though it isn't included in the manuscript, it was an important part of our process to get to our model and how we decided not to include it.
3. In the previous `figures` module, it included an important analysis used in a grant, so it might not be the best to delete it from the repo. I recommend moving it to the 0.data_analysis module so that it can still be referenced.
4. Most of these modules now do not include READMEs (except for the `3.figures` module, which I don't think needs one yet). I recommend adding back descriptive READMEs per module prior to merging this refactor.

Overall, I think most of the data exploration should be kept. From my perspective, it would be okay to remove the old ML models that we don't use and are not optimal, since we don't plan to discuss model optimization in the manuscript.

**Review by MikeLippincott — COMMENTED** [review]
I left a comment with questions regarding the deleted files. I am requesting changes for some sort of change log for deleted file and rationale for the deletion of that file. I think for tracking files and for understanding why files are being deleted this would be a great option.

**Comment by MattsonCam** [comment]
> Questions:
> 
>     * Why remove older analysis?
Older analysis tend to clutter the repo and detract from the main story as it relates to NF1, especially for datasets that don't provide much value due to sample size, quality, etc...
>     * Could these be used in the future?
Of course, statistical tests, exploring feature importances, and other analysis are common in many project, and could be applied to other datasets.
>     * Are there any analysis that could be used as supplemental?
Some of them probably could be used as supplemental, but I don't think it would be very useful to the story. Some of these analysis are also duplicates.
>     * Could these analyses be refactored to a misc analysis folder?
Possibly, see response to previous question above.
> Negative results or analyses that did not work or were published are still important analyses and thus might have reason to stay in the repo depending on how you answer the above questions.

Yes, negative results can also be interesting.

**Comment by MattsonCam** [comment]
> Here is a screenshot of what the repo will look like after this PR: image Some comments based on the new structure of the repo from this branch:
> 
>     1. I would recommend not having the "classify_genotypes" module if you plan on only having one method. It looks a bit odd to me in the screenshot to have two modules with the same folder name inside.
Agreed, I'll change that
>     2. In the 0.data_analysis repo, I recommend that you should leave the plate 4 analysis. Even though it isn't included in the manuscript, it was an important part of our process to get to our model and how we decided not to include it.
Which analysis in `0.data_analysis` do you mean specifically? In the last NF1 manuscript meeting, one of my action items was to close the plate 4 correlations analysis pr. I think most of the plate 4 analysis deleted were older correlation analysis.
>     3. In the previous `figures` module, it included an important analysis used in a grant, so it might not be the best to delete it from the repo. I recommend moving it to the 0.data_analysis module so that it can still be referenced.
It looks like all of the code in the `figures` module are used to visualize plate 4 correlations. See my response to number 2 above.
>     4. Most of these modules now do not include READMEs (except for the `3.figures` module, which I don't think needs one yet). I recommend adding back descriptive READMEs per module prior to merging this refactor.
This pr is for removing older analysis. I'll be adding the READMEs in a future pr.
> Overall, I think most of the data exploration should be kept. From my perspective, it would be okay to remove the old ML models that we don't use and are not optimal, since we don't plan to discuss model optimization in the manuscript.

I agree, I have some code I haven't pushed to gh sitting on my local pc, which I may also create pr(s) for.

**Comment by jenna-tomkinson** [comment]
>Which analysis in 0.data_analysis do you mean specifically? In the last NF1 manuscript meeting, one of my action items was to close the plate 4 correlations analysis pr. I think most of the plate 4 analysis deleted were older correlation analysis.

I just thought of this while looking at the repo, so my only concern was not having access to data that we used in a grant. This might be a conversation at another time since we still will have access to the data in the history. I would recommend keeping the older analysis for now in case we believe it to be necessary to include the updated data. There is no right or wrong answer here from my perspective.

**Comment by MattsonCam** [comment]
> > Which analysis in 0.data_analysis do you mean specifically? In the last NF1 manuscript meeting, one of my action items was to close the plate 4 correlations analysis pr. I think most of the plate 4 analysis deleted were older correlation analysis.
> 
> I just thought of this while looking at the repo, so my only concern was not having access to data that we used in a grant. This might be a conversation at another time since we still will have access to the data in the history. I would recommend keeping the older analysis for now in case we believe it to be necessary to include the updated data. There is no right or wrong answer here from my perspective.

@jenna-tomkinson I don't think I have removed any analysis we still need, and we eventually need to software garden this repo. With that said, since you are the project lead and are suggesting to keep the older analysis for now, I will keep this pr open, and wait for you to schedule next steps. This may be in the form of a conversation or pr comments.

**Comment by jenna-tomkinson** [comment]
@MattsonCam Let's plan on software gardening more now, and we can get that analysis back later if necessary. I agree this repo for the manuscript should be clean and concise, and keeping the old data isn't as helpful as say, adding that closed PR with the plate 4 data correlations back later.

We might even consider moving plate 4 analysis into the image-analysis repo if that makes sense. We have time to make a final decision, and I think your original idea to remove plate 4 is good after thinking about it more given the scope of the manuscript.

**Review by jenna-tomkinson — APPROVED** [review]
I think this has been cleaned up really well since I noticed there was a lot of old plate 1 and 2 models. I like that duplicate analysis was removed like UMAPs. I think most of the stuff removed are out of scope of the manuscript (but can be added back later if needed).

I am going to approve this as the changes do not impact the code to generate final manuscript figures (as far as I can tell). As well, I don't think this needs to be looked at again, but my two important things I have for you to address prior to merge is:

1. Please make sure to include the READMEs prior to merging, or the READMEs will be the next PR. Let me know either way. 
2. Feel free to remove the old plate 4 correlations for now in 0.data_analysis. This can be further discussed at another manuscript meeting once we have another draft ready.

Nice job gardening the repo! 🏡

**Comment by MattsonCam** [comment]
> @MattsonCam Let's plan on software gardening more now, and we can get that analysis back later if necessary. I agree this repo for the manuscript should be clean and concise, and keeping the old data isn't as helpful as say, adding that closed PR with the plate 4 data correlations back later.
> 
> We might even consider moving plate 4 analysis into the image-analysis repo if that makes sense. We have time to make a final decision, and I think your original idea to remove plate 4 is good after thinking about it more given the scope of the manuscript.

Sounds good @jenna-tomkinson! We can always talk more about the other repo later if we want

**Comment by MattsonCam** [comment]
> I think this has been cleaned up really well since I noticed there was a lot of old plate 1 and 2 models. I like that duplicate analysis was removed like UMAPs. I think most of the stuff removed are out of scope of the manuscript (but can be added back later if needed).
> 
> I am going to approve this as the changes do not impact the code to generate final manuscript figures (as far as I can tell). As well, I don't think this needs to be looked at again, but my two important things I have for you to address prior to merge is:
> 
>     1. Please make sure to include the READMEs prior to merging, or the READMEs will be the next PR. Let me know either way.
> 
>     2. Feel free to remove the old plate 4 correlations for now in 0.data_analysis. This can be further discussed at another manuscript meeting once we have another draft ready.
> 
> 
> Nice job gardening the repo! 🏡

Thanks @jenna-tomkinson, will do!

**Comment by MattsonCam** [comment]
> I left a comment with questions regarding the deleted files. I am requesting changes for some sort of change log for deleted file and rationale for the deletion of that file. I think for tracking files and for understanding why files are being deleted this would be a great option.

Sounds good, I don't think a changelog belongs in main, so I'll include it here for reference:

# Changelog

These are the changes made in this pr. These changes were completed in decending order, starting from the top of this document.

### Removed
- 0.data_analysis/construct_phenotypic_expression_plate_4_fs_data
    - Justification: We decided to no longer include correlations of plate 4 constructs
- 0.data_analysis/plates_1_2_sig_test_nf1_sc_all_cellprofiler.ipynb
    - Justification: Plates beyond 1 and 2 have more samples are believed to be better quality
- 0.data_analysis/data
    - Justification: Plates beyond 1 and 2 have more samples are believed to be better quality
- 0.data_analysis/figures
    - Justification: Plates beyond 1 and 2 have more samples are believed to be better quality
- 0.data_analysis/nbconverted
    - Justification: Plates beyond 1 and 2 have more samples are believed to be better quality
- 0.data_analysis/plate_projection_cp_fs_data
    - Justification: Plates beyond 1 and 2 have more samples are believed to be better quality
- figures
    - Justification: We decided to no longer include correlations of plate 4 constructs
- 0.data_analysis/plates_1_2_sig_test_nf1_sc_all_cellprofiler.ipynb
    - Justification: Plates beyond 1 and 2 have more samples are believed to be better quality
- 1.train_models/linear_reg_plate_1_2_norm_data
    - Justification: Plates beyond 1 and 2 have more samples are believed to be better quality
- 1.train_models/classify_genotypes/generate_eval_data.ipynb
    - Justification: This notebook aimed to correct an absent bug
- 1.train_models/classify_genotypes/data/nf1_final_model_eval_data.parquet
    - Justification: This data manifested from a notebook aiming to correct an absent bug
- 1.train_models/classify_genotypes/model_data.parquet
    - Justification: This data manifested from a notebook aiming to correct an absent bug
- 1.train_models/classify_genotypes/nbconverted/generate_eval_data.py
    - Justification: This code aimed to correct an absent bug
- 1.train_models/classify_genotypes/model_data.parquet
    - Justification: This data manifested from a notebook aiming to correct an absent bug
- 1.train_models/log_reg_plates_cp_fs_data
    - Justification: This folder aimed to train genotype classification models on individual plates and the combined 3 and 3 prime plates. Since then we have developed a more generalizable model by training on multiple plates
- 2.evaluate_models/classify_genotypes/genotype_probabilities
    - Justification: We decided to no longer include plate 4 data
- 2.evaluate_models/classify_genotypes/nbconverted/plate_4_sirna_genotype_probabilities.py
    - Justification: We decided to no longer include plate 4 data, so we are not interested in the model evaluation code
- 2.evaluate_models/classify_genotypes/plate_4_sirna_genotype_probabilities.ipynb
    - Justification: We decided to no longer include plate 4 data, so we are not interested in the model evaluation code
- 2.evaluate_models/log_reg_plates_cp_fs_data
    - Justification: This folder aimed to evaluate genotype classification models on individual plates and the combined 3 and 3 prime plates. Since then we have developed a more generalizable model by training on multiple plates
- 2.evaluate_models/classify_genotypes/model_evaluation_data/confusion_matrix_hyperparameters.parquet
    - Justification: This data manifested from a notebook aiming to correct an absent bug
- 2.evaluate_models/classify_genotypes/model_evaluation_data/metrics_hyperparameters.parquet
    - Justification: This data manifested from a notebook aiming to correct an absent bug
- 2.evaluate_models/classify_genotypes/model_evaluation_data/precision_recall_hyperparameters.parquet
    - Justification: This data manifested from a notebook aiming to correct an absent bug
- 1.train_models/utils
    - Justification: These utils were used for training older genotype classification models
- 1.train_models/log_reg_plates_3_3p_5_cp_norm_data
    - Justification: The splitting approach for training this model was not efficient and needed to be refined. Due to time constraints we decided not to refine this splitting approach
- 2.evaluate_models/log_reg_plates_3_3p_5_cp_norm_data
    - Justification: The splitting approach for training this model was not efficient and needed to be refined. Due to time constraints we decided not to refine this splitting approach
- 1.train_models/nbconverted
    - Justification: Code from an old model trained on plate 3 data
2.evaluate_models/log_reg_plate_3_3p_cp_renorm_fs_data
    - Justification: This is the evaluation of the model trained on the Null and WT cells of plates 3 and 3p. Since then we have developed a more generalizable model by training on multiple plates
- 3.interpret_models
    - Justification: Location where older models were interpreted. Since then, we interpret models in `3.figures`

### Moved
- 1.train_models/classify_genotypes/* to 1.train_models/
    - Justification: Simplify the folder structure
- 2.evaluate_models/classify_genotypes/* to 2.evaluate_models/
    - Justification: Simplify the folder structure

**Comment by MattsonCam** [comment]
Thanks @MikeLippincott and @jenna-tomkinson, merging now!

**Pull request merged**
