### PR TITLE
Add main figure 5

### PR DESCRIPTION
**Pull request by jenna-tomkinson**
# Add main figure 5

In this PR, main figure 5 for the manuscript and conference presentation was generated, which shows the evaluation of the model on the siRNA data from plate 4. I am prepared for any and all nit-picks on the figure to make it as clear and manuscript-ready as possible! 😄

### CODE REVIEW

**Comment by gwaybio** [comment]
Figure nitpicks

## Panel A

- It's pretty tough to see the thin lines. Rather than distinguish lines based on width, I recommend distinguishing based on alpha. 
- Would it be possible to add small red stars as points to the x axis (somewhere? 🤷 ) that points to the doses we visualize in panel C?
- I would recommend shifting the language in the legend a bit. For example `Construct` should probably be `Target` and `NF1 Construct 1` probably should just be `NF1`.
- The x axis should probably be rearranged just a bit `siRNA concentration (log10 nM)`
- I think this would more accurately describe the y axis label:`%NF1\n(normalized to scramble)`? (writing out norm -> normalized)

## Panel B 

- I'd simplify the facet label (`NF1` instead of `NF1 construct 1`) -> we'll have to update this if we get more data
- I'm a bit confused what we're seeing here. A couple questions which may illuminate: 
  - Why are there so many more scramble points than replicate points
  - What dose of the NF1 construct are we visualizing here? Perhaps it is worth adding all replicate comparisons (all doses) to the dark blue box? I can also see a world in which we show correlations for each dose individually in this panel somewhere
  - Do you know what is going on in the white box? There is an interesting grouping of points that seem to be distributed evenly. 
- The legend title `Comparison` probably would be better to be `Pairwise\ncomparison`

## Panel C

- This is a very interesting visualization! Especially interesting to see the differences in across wells...
- I wonder if a `geom_violin()` + `geom_point()` would be more effective than just a `geom_box()` - we would like to see the underlying distributions of individual cells per well
- Adding the red stars to panel A would be particularly informative for how to interpret this result!
- While I think splitting by well is interesting and we should include, it might be better as a supplementary figure. I can imagine visualizing the trend per dose in the main figure, but splitting out by well in the supplement. We can include a platemap figure as well, since it seems like there could be well position biases (maybe the upper half of the plate has higher WT probability?)

**Comment by gwaybio** [comment]
More nitpicks (final)

## Panel A

- Title case in x axis label
- Construct to Target
- Fix weird lines in line graph. I think this has something to do with the `groups` variable in the `geom_line()` call.

## Panel B

- call `geom_line()` after `geom_boxplot()` to move dotted line in front of box
- Consider adding back the no controls

## Panel C

- Title case in both axis labels
- Consider dropping the alpha slightly and increasing the width of the jitter. It's a bit tough to distinguish high density from low density regions

**Review by gwaybio — APPROVED** [review]
Good to merge when you're happy with figure

**Comment by jenna-tomkinson** [comment]
@gwaybio Thanks for the review! I will be merging now!

**Pull request merged**
