### PR TITLE
Add main figure 2

### PR DESCRIPTION
**Pull request by jenna-tomkinson**
# Add main figure 2

In this PR, main figure 2 is generated and ready to be nit-picked! Thanks!

### CODE REVIEW

**Comment by gwaybio** [comment]
Nitpicks

The way the figure is currently laid out places the primary focus on different plates. I'm not sure that's the message we want to state! I think the message needs to focus more on genotype. We can show in a supplemental figure the influence of plate.

So, my recommendations are to:

## Panel A

- Show only one UMAP, make genotype different colors

## Panel B

- Show only one facet, with the following categories for curves: 1) Same genotype same plate, 2) Same genotype different plate, 3) Different genotype same plate, 4) Different genotype different plate

We also should dig a bit into the bimodal curves for plate 3 prime - super interesting!! 

## Other

I wonder if there is room here to add a descriptive panel. Perhaps a new panel A (the others become B and C), which can do some heavy work describing how many cells of either genotype we analyzed total (and per plate). I imagine a bar chart would be good.

We can chat about this (and all other suggestions) separately as well! Looking good!

**Comment by gwaybio** [comment]
Looking much better! A few more nitpicks

## Panel A

- Can you add (to the beginning sets of bars) a `Total` (indicating all plates)
- Can you add text to the top of each bar indicating the exact count?
- I would recommend recoding the plate numbers to reduce confusion. Maybe name them plates A-D?
- The bars for plate 5 do not show siRNA treatments, right?

## Panel B

- ⭐ 

## Panel C

- I'm a bit thrown off by the colors... maybe tweaking this to have only two colors and showing a ggridge facet of same plate and different plate? Does this make sense?
- The legend title "Combination" lacks specificity. Perhaps (and once you shift the plot slightly as I recommend above), the title can be: `Is the\npairwise\ncomparison\nfrom the\nsame genotype?` (or something super specific liek this)

**Review by gwaybio — APPROVED** [review]
One final nitpick - otherwise LGTM and please merge when you're happy!

I was hoping to see totals from all plates for each genotype (not totals per plate)

**Comment by jenna-tomkinson** [comment]
@gwaybio Thank you for the reviews! All nit-picks have been addressed. I will be merging now!

**Pull request merged**
